# Cross validation scores for classifier model

### Starting a model first

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

In [2]:
model = pd.read_csv("../Data/heart-disease.csv")
X = model.drop("target", axis=1)
y = model["target"]

In [4]:
model = RandomForestClassifier(n_estimators=100)

## (i) Cross validated accuracy

In [6]:
np.random.seed(42)
cv_acc = cross_val_score(model, X, y, cv=5, scoring="accuracy")
cv_acc

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [7]:
np.mean(cv_acc)

0.8248087431693989

## (ii) Cross validated precision

In [9]:
np.random.seed(42)
cv_precision = cross_val_score(model, X, y, cv=5, scoring="precision")
cv_precision

array([0.82352941, 0.93548387, 0.84848485, 0.79411765, 0.76315789])

In [10]:
np.mean(cv_precision)

0.8329547346025924

## (iii) Cross validated recall

In [11]:
np.random.seed(42)
cv_recall = cross_val_score(model, X, y, cv=5, scoring="recall")
cv_recall

array([0.84848485, 0.87878788, 0.84848485, 0.81818182, 0.87878788])

In [16]:
np.mean(cv_recall)

0.8545454545454545

In [18]:
np.random.seed(42)
model = RandomForestClassifier(n_estimators=100)
cv_r2 = cross_val_score(model, X, y, cv=5, scoring = None)
cv_r2

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [20]:
np.mean(cv_r2)

0.8248087431693989

### Mean squared error

In [14]:
cv_mse = cross_val_score(model, X, y, cv=5, scoring = "neg_mean_squared_error")
cv_mse

array([-0.21311475, -0.13114754, -0.19672131, -0.21666667, -0.23333333])

In [15]:
np.mean(cv_mse)

-0.1981967213114754

In [21]:
cv_mae = cross_val_score(model, X, y, scoring = "neg_mean_absolute_error")
cv_mae

array([-0.21311475, -0.13114754, -0.19672131, -0.21666667, -0.23333333])

In [22]:
np.mean(cv_mae)

-0.1981967213114754