# 1. Accuracy

In [3]:
# Standard imports 
import pandas as pd
import numpy as np

In [4]:
# Initiating a model
model = pd.read_csv("../data/heart-disease.csv")
model.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
# Splitting into X & y axes
X=model.drop("target",axis =1)
y=model["target"]
X.head(), y.head()

(   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
 0   63    1   3       145   233    1        0      150      0      2.3      0   
 1   37    1   2       130   250    0        1      187      0      3.5      0   
 2   41    0   1       130   204    0        0      172      0      1.4      2   
 3   56    1   1       120   236    0        1      178      0      0.8      2   
 4   57    0   0       120   354    0        1      163      1      0.6      2   
 
    ca  thal  
 0   0     1  
 1   0     2  
 2   0     2  
 3   0     2  
 4   0     2  ,
 0    1
 1    1
 2    1
 3    1
 4    1
 Name: target, dtype: int64)

In [7]:
# Calling classifier model for Model training
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)
model = RandomForestClassifier(n_estimators=100)

In [8]:
# Calling cross_val_score to make preediction of the model
from sklearn.model_selection import cross_val_score
cross_val_score = cross_val_score(model, X, y, cv = 2)
np.mean(cross_val_score)

0.8348727779714187

# 2. Area under the ROC Curve
#### Area under the Reciever operationg characteristic curve
##### AUC/ROC

#### ROC curves are comparisons of model's true positive versus false positive rate
||Prediction|Truth|
|---|---|---|
|True Positive |1|1
|Flase Positive|1|0|
|True Negative |0|0|
|False Negative|0|1|

In [9]:
# Create test & training dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2)

In [10]:
# Fitting the classifier model
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

RandomForestClassifier()

In [11]:
# making predictions with probabilities
from sklearn.metrics import roc_curve
y_probs = model.predict_proba(X_test)
y_probs[:10], len(y_probs)

(array([[0.  , 1.  ],
        [0.44, 0.56],
        [0.78, 0.22],
        [0.28, 0.72],
        [0.95, 0.05],
        [0.9 , 0.1 ],
        [0.91, 0.09],
        [0.53, 0.47],
        [0.04, 0.96],
        [0.23, 0.77]]),
 61)

In [14]:
y_probs_positive = y_probs[:,1]
y_probs_positive[:10]

array([1.  , 0.56, 0.22, 0.72, 0.05, 0.1 , 0.09, 0.47, 0.96, 0.77])

In [18]:
# Calculating tpr, fpr and threshold
fpr, tpr, threshold = roc_curve(y_test, y_probs_positive)

#chack false positive rate
fpr

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05263158, 0.05263158, 0.05263158, 0.15789474, 0.15789474,
       0.21052632, 0.21052632, 0.21052632, 0.21052632, 0.26315789,
       0.26315789, 0.31578947, 0.31578947, 0.42105263, 0.42105263,
       0.47368421, 0.63157895, 0.73684211, 1.        ])