In [39]:
import pandas as pd
import numpy as np

In [40]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,9])
an=np.array([[a1], [a3]])
an

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [41]:
a_ndim = np.array([[[a3]+[a2]+[a1]],[[a1]+[a3]+[a2]]])
a_ndim

array([[[[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [7, 8, 9],
         [4, 5, 6]]]])

In [42]:
a2_ndim =np.array([[[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]],
                   [[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]],
                   [[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]]])
a2_ndim

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]],

       [[3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9]]])

In [43]:
random_array = np.random.randint(0, 100, size=(99,100))
random_array

array([[74,  2, 61, ..., 46, 85, 39],
       [12, 32,  2, ...,  1, 61, 78],
       [93, 85, 60, ..., 97, 43, 31],
       ...,
       [39, 41, 19, ..., 95, 91, 32],
       [97, 31, 84, ..., 55, 64, 62],
       [88, 55,  5, ..., 50, 30, 50]])

In [44]:
arr_series = pd.DataFrame(random_array)
arr_series

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
0   74   2  61  28   0  41  72  35  46  97  ...  90  50  22  35   5  56  47   
1   12  32   2  83  94  84   3  88  14  97  ...  54  72   1  59  36  34  73   
2   93  85  60  23  64  44  25  60  55  27  ...  59  68  27  53  66   2  54   
3   48  63  47  46  42  83  33  14  25  18  ...  23  20  73  15  66  23  27   
4   79  22  42  41  88  36  22  10  93  11  ...  66  87  77   9  71  35  18   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
94  22  90  54  75  65  97  99  91  89   0  ...  60  24  83  44  68  13  84   
95  12  22  51   1  21  22   9  64  35  98  ...  96  63  16  53  32  35  62   
96  39  41  19  99  98  11  45  32  44  18  ...  21  50  60  22  37  12   5   
97  97  31  84  13  62  19  95  69   2  62  ...   1   7  57  18   0   8  56   
98  88  55   5  49  92  71  48  70  35  66  ...  34  73  72  55  11  18   7   

    97  98  99  
0   46  85  39  
1    1  61  78  
2   97  43  31  
3    3  51  92  
4    6  80   4  
..  ..  ..  ..  
94  17  70  74  
95   7  96  30  
96  95  91  32  
97  55  64  62  
98  50  30  50  

[99 rows x 100 columns]

In [45]:
arr_series.to_csv("random_csv_byPython", index=False)

## Sorting an array

In [46]:
read_csv=pd.read_csv("random_csv_byPython")
read_csv

0   1   2   3   4   5   6   7   8   9  ...  90  91  92  93  94  95  96  \
0   74   2  61  28   0  41  72  35  46  97  ...  90  50  22  35   5  56  47   
1   12  32   2  83  94  84   3  88  14  97  ...  54  72   1  59  36  34  73   
2   93  85  60  23  64  44  25  60  55  27  ...  59  68  27  53  66   2  54   
3   48  63  47  46  42  83  33  14  25  18  ...  23  20  73  15  66  23  27   
4   79  22  42  41  88  36  22  10  93  11  ...  66  87  77   9  71  35  18   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
94  22  90  54  75  65  97  99  91  89   0  ...  60  24  83  44  68  13  84   
95  12  22  51   1  21  22   9  64  35  98  ...  96  63  16  53  32  35  62   
96  39  41  19  99  98  11  45  32  44  18  ...  21  50  60  22  37  12   5   
97  97  31  84  13  62  19  95  69   2  62  ...   1   7  57  18   0   8  56   
98  88  55   5  49  92  71  48  70  35  66  ...  34  73  72  55  11  18   7   

    97  98  99  
0   46  85  39  
1    1  61  78  
2   97  43  31  
3    3  51  92  
4    6  80   4  
..  ..  ..  ..  
94  17  70  74  
95   7  96  30  
96  95  91  32  
97  55  64  62  
98  50  30  50  

[99 rows x 100 columns]

In [63]:
arr=np.random.randint(10,size=(3,5))
arr

array([[5, 7, 9, 0, 0],
       [4, 0, 7, 7, 7],
       [9, 1, 5, 7, 9]])

In [61]:
#np.sort(arr)

In [51]:
#np.argsort(arr)

In [64]:
arr

array([[5, 7, 9, 0, 0],
       [4, 0, 7, 7, 7],
       [9, 1, 5, 7, 9]])

In [65]:
np.argmax(arr, axis=0)

array([2, 0, 0, 1, 2])

In [66]:
np.argmax(arr, axis=0)

array([2, 0, 0, 1, 2])

In [67]:
np.argmax(arr)

2

## Turn an image into array(numpy array or ndarray)

In [76]:
from matplotlib.image import imread

In [82]:
image = imread("Photo 4.jpg")
image

array([[[253, 253, 253],
        [255, 255, 255],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [254, 254, 254],
        [255, 255, 255]],

       [[255, 255, 255],
        [250, 250, 250],
        [246, 246, 246],
        ...,
        [253, 253, 253],
        [254, 254, 254],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [253, 253, 253],
        ...,
        [253, 253, 253],
        [254, 254, 254],
        [255, 255, 255]],

       ...,

       [[251, 255, 255],
        [246, 250, 253],
        [250, 254, 255],
        ...,
        [252, 254, 253],
        [253, 255, 254],
        [254, 255, 255]],

       [[240, 244, 247],
        [250, 254, 255],
        [252, 255, 255],
        ...,
        [252, 254, 253],
        [253, 255, 254],
        [254, 255, 255]],

       [[253, 254, 255],
        [252, 253, 255],
        [243, 247, 246],
        ...,
        [252, 254, 253],
        [253, 255, 254],
        [254, 255, 255]]

In [84]:
print(type(image))

<class 'numpy.ndarray'>
